### ISSUE TITLE
Password Grant authorization not working as expected

### ISSUE THREAD

**Issue by dehuszar** [justingreerbbi/wordpress-oauth-server#10]
I am trying to utilize the password-grant authorization, but all attempts to send form data get discarded and in my response, I'm being forwarded to a login form (though I can see some of my form data in my request header).  

My preference is to handle the login process on the front-end and just encrypt the transmission.  How can I avoid the redirect to the login form?

**Comment by justingreerbbi** [comment]
The new plugin merge just now is a better suit for your needs. Please make a backup of all DB tables and plugin files. You are more than welcome to stay on the older version if you indeed use it.

There is little to no legacy support for older version with the latest merge.
