### ISSUE TITLE
Logout method for the API

### ISSUE THREAD

**Issue by carlouni** [justingreerbbi/wordpress-oauth-server#11]
Since the login creates a session on the Wordpress site, I believe, there should be a method logout within the oAuth API that gives as a response a logout url. For example: 

Request:
http://yourdomain.com/oauth/logout?access_token=6f6d8a22c3b127034fb8dc137766625268631d0b

Response:
{"logout_url":"http://yourdomain.com/wp-login.php?action=logout&redirect_to=http://oauthclientsite.com&_wpnonce=5a919040d6"}

Not sure about other users, but I needed it on my site so I had to make changes to the plugin to achieve this since building a different plugin that reuses the classes defined on your plugin was going to be harder.

Any plans for creating a Resource API that integrates with the oAuth server?

**Comment by justingreerbbi** [comment]
I wanted to reply and close this issue in the wake of 3.0.0 release of the plugin. Please refer to [http://wp-oauth.com](http://wp-oauth.com) for documentation on how to extend the resource API to fit your needs.

**Comment by carlouni** [comment]
Hi Justin, updated to the new version and it seems more flexible. Moved my logout method as an extension of the API using a plugin. That will allow me to update future version without any issue. Good work.

Any plans to implement an option to validate the redirect_uri just at the domain level ? Is this allowed by the OAuth 2 especifications ? Had to tweak the plugin to allow me to do that making sure it only redirects to my own subdomains :) .

**Comment by ido-ran** [comment]
Hi,
I'm also using Justin's OAuth plugin, I've checked the `Require Exact Redirect URI` option which ensure the client ask to be redirected to the URL I've setup in the Clients tab. That is stronger than just ensuring you are on the same domain.

Do you agree?

**Comment by carlouni** [comment]
Well, In theory, I should be using that option but my problem is that I'm providing a service in a different application where each user has its own subdomain and I'm just using one oauth client since all the subdomains run on a same PHP application. The redirect response that I should get from WP OAuth is something like http://username.mydomain.com/login/?code=authentication_code

**Comment by ido-ran** [comment]
What about using different clients for each of your services?
I am using several clients mostly for testing purposes but it still works great.
Also for test purpose I'm using localhost which is not on the same domain.

**Comment by carlouni** [comment]
Yes, that would be another great solution but in that case I have to automatize the processes of generating the oauth credentials automatically when the user signs up to the service. I may do it at some point when I have more time available to do the coding. So far I'm happy with the WP OAuth plugin. Skimmed the OAuth 2 specification and this plugin is compliance with it.

**Comment by justingreerbbi** [comment]
@carlouni Thanks for explaining what you are needing to do. The plugin is in its early stage so there, so in a way it is primitive and adheres to the strict standards of OAuth 2.0.

With this said, OAuth 2.0 uses the redirect_uri parameter which us a layer of security that separates OAuth 1.0 and OAuth 2.0. I am going to do so tests this morning and hopefully I will have a solution for you.

**Comment by justingreerbbi** [comment]
I have updated the the master branch with the ability to hook into the redirect_uri validation and either completely override it or do you own custom validation (sub domains, sub directories, etc.).

You can find about the filter by visiting http://wp-oauth.com/documentation/server-api/filters/. You must update your plugin. I have made the change but have not yet updated the version number. I will be re-arranging the repo to have a development and tagged version structure shortly.

**Comment by carlouni** [comment]
Hi Justin, that's awesome. I'll have a look at it and customize my redirect_uri validation.
