### ISSUE TITLE
Integration with WP-API ?

### ISSUE THREAD

**Issue by EugeneLiang** [justingreerbbi/wordpress-oauth-server#14]
Hi there, 

I was wondering if your plugin can be integrated with http://wp-api.org/ ?

For example, after performing the authentication, I will have the user data and the access token.

How do i use this access token and perform GET/POST requests ?

So if your plugin can be integrated with http://wp-api.org, how should I go about doing it ?

If not, I was wondering how do i extend your plugin to include JSON apis in a similar fashion as wp-api ?

Thanks a lot, great work!

**Comment by justingreerbbi** [comment]
The latest version of WP OAuth Server now works with WP API. Visit https://wp-oauth.com/knowledge-base/authenticating-with-wp-rest-api/ for an example of how it works.

The repo here is a bit behind. I will be updating the repo here for the community version. The plugin has grown exponentially over the past year and soon will be slit into community and commercial. None he less for the time being, it is working with both the light and pro version.

I am closing for my personally sanity.

Thanks
