### ISSUE TITLE
state parameter is required

### ISSUE THREAD

**Issue by ido-ran** [justingreerbbi/wordpress-oauth-server#19]
It is currently require to pass state parameter to the authorize method.
I have a use case in which no state is require, for simple authentication.

It will be easier to use this plugin if state parameter will be optional.

**Comment by justingreerbbi** [comment]
I have merged developer into master. The new plugin now provides a option in the wp-admin->OAuth Server settings to enforce or no enforce the state parameter. 

The new plugin is different and has not legacy support. Make a backup if your DB tables and plugin files before updating.
