### ISSUE TITLE
/oauth/request_access/ require trail slash

### ISSUE THREAD

**Issue by ido-ran** [justingreerbbi/wordpress-oauth-server#20]
It is required to add a trailing slash to the request_access method.
The plugin does return a redirect to the correct URL but in the default nodeJS library I use (passport) the http client does not follow redirect by default.

I'm not sure what is more correct - with or without slash.

**Comment by justingreerbbi** [comment]
Changed the requirement for a trailing slash when entering the redirect URI option.

Before updating please be sure to backup all DB tables and plugin files. The new plugin does not have legacy support for older versions of the plugin
