### ISSUE TITLE
In WP-Admin under Clients tab the edit link of a client does not work

### ISSUE THREAD

**Issue by ido-ran** [justingreerbbi/wordpress-oauth-server#22]
Repro:
1. Go into WP-Admin (that has the plugin of course)
2. Go into Clients tab
3. Add a client
4. Hover with the mouse over the client's row and press the `edit` link

Expected Result:
Show a dialog which allows to change some of the information about the client

Actual Result:
Nothing shows, the page jump to the top.

**Comment by justingreerbbi** [comment]
Ido. Send me an email for future plans. Last supported version 3.0.3 has this ability
