### ISSUE TITLE
wordpress oauth login for different platform

### ISSUE THREAD

**Issue by zionnite** [justingreerbbi/wordpress-oauth-server#27]
hello, wonderfull effort u made there  but i was thinking if there is a way to implement wordpress api with a different app that is not build on wordpress....

**Comment by justingreerbbi** [comment]
Absolutely!! The plugin is an API that allows for anything to connect to it as long as it follows the OAuth 2.0 workflow. What platform are you looking to connect to it?

**Comment by zionnite** [comment]
thank u sir for the instant reply(am really gratefull) i want to connect to codeigniter framework or if another way round do it procedurally

**Comment by zionnite** [comment]
and again sir..... how can i get the authentication code; user credential ; client credential etc to make the script work.... thanks for helping me

**Comment by justingreerbbi** [comment]
Codeignitor is able to connect to WP OAuth Server without issues. WP OAuth Server is a provider so you will need to write the client side of it for codeignitor.

If you go back through some older commits, there was a sample client in the code base.

**Comment by justingreerbbi** [comment]
Brent Shaffer also has good documentation of how a OAuth Server works and how to connect to one.
http://bshaffer.github.io/oauth2-server-php-docs/cookbook/

**Comment by zionnite** [comment]
thank u sir... i will quickly look at them now .... i will notify u when i found something.....
thanks again sir

**Comment by justingreerbbi** [comment]
your welcome. I am hoping to have client frameworks for download within the next few months as well.

**Comment by zionnite** [comment]
ok....
but sir since u have help me to this extent let me explain why i need this wordpress api....
i registered for this year google code of summer so we were given project to work one and u need to pick at least one project so i pick OAUTH LOGING ON PHP 
To develop a simple web app that implements oauth login to systems using facebook api, google api, wordpress, twitter, yahoo, linkedin. You should be able to retrieve at least, the username from these account and create meaningful data around it.....
so please sir do u have any advise or ideal i can accomplish this task

**Comment by justingreerbbi** [comment]
I think I can help you out. I do not have the free time right now but I will go back in the repo and see if I can find my PHP OAuth Client that can be used to connect to WordPress OAuth Server. Please give me 24-48 hours and I should have you something that you are looking for. 

Until I an get you the test client, I recommend reading up on as much as you can about how OAuth 2.0 works, specifically around grant types and the authentication flow of each.

Good Luck

**Comment by zionnite** [comment]
thank u sir

**Comment by justingreerbbi** [comment]
I have created a new repo where I will start storing any test clients for WordPress OAuth server. I found an old PHP client I did and it is now push to the repo here https://github.com/justingreerbbi/wordpress-oauth-server-clients/.

Right now it is the only client in the repo (Generic PHP Client)

**Comment by justingreerbbi** [comment]
Sorry. I forgot to share the WP OAuth site link. You can find more detailed information about using WordPress OAuth server there. You will also be able to find examples as well.

http://wp-oauth.com

**Comment by zionnite** [comment]
thank u sir am checking it right now

**Comment by zionnite** [comment]
sir thank u .... no body has ever offered me an help this way before... i
say again thank U......
i am beginning to love WordPress framework and i will love to have u as my
mentor....
but one thing sir ....like Facebook api when i registered they gave me
secret id and client id so for this of WordPress how am i going to get the
client secret  id and client id

**Comment by justingreerbbi** [comment]
You will need to install WordPress oauth server on you WordPress site. Then
you can create a client in the backend under the oauth server settings.
Right now you have to manually create the client height the options but
here axon I plan on writing g an extension to do it when I user registers
for the site.

sent from my phone. Sorry for misspellings and or being sort.

**Comment by zionnite** [comment]
good morning sir.... how was ur nite....
am sorry i would have already give u my testimony by now but my Cpanel is
giving me some set back (when i login  it bouncing me back and said IP
address changes).... when am done i notify u
