### ISSUE TITLE
Mulit-press support

### ISSUE THREAD

**Issue by sosensible** [justingreerbbi/wordpress-oauth-server#28]
This may already be supported, but I did not find that in the docs. Without explicit support we would like to know of course before using it on a multi-site.

**Comment by justingreerbbi** [comment]
Hi, 
The server does work on MS at the user level but is not officially supported yet. You can try to install the the server and see if it is a fit but I assume there would be limit is any success as we have not tested on MS.

This is on the list of todo's for the project. Right now, I have been swamped with projects so I have not had as much time as I would have like for the OAuth Server. You are more than welcome to fork the repo and modify to fit your needs. If you come up with something that you feel other may find helpful, I will gladly link to it and or merge it into the repo.

Thanks

**Comment by zionnite** [comment]
ok... thqnks friends, my eyes are open

**Comment by justingreerbbi** [comment]
Leaving open to make sure the request stays visible.

**Comment by hefejeff** [comment]
The server does work on the MS but I am having an issue with it only working on the main site and not on the sub sites of MS.  This has been driving me crazy for days.  The server works fine when I try authenticate request to the main site (captzapp.com) but I get 401 error with the message "Token is not registered for the given consumer" whenever I try on any of the subsites (test.captzapp.com).

**Comment by justingreerbbi** [comment]
The main issue with is with how WP OAuth Server utilizes tables in the DB. It currently is not setup to handle multi blog which will cause all kinds of unknown headaches when trying to get it to work properly.

You error "Token is not registered' must be custom as I am not sure it is even in the core code base.

**Comment by hefejeff** [comment]
It looks like I am using another plugin Oauth1 which is suggested to use
with WP REST API.  Sorry about that.  That being said I think that I have
an idea the could make both plugins work with multisite networks.

First of all authentication works on the main site but not the others.  I
understand that authentication on wordpress MS networks is network wide.  I
think that if the authentication were forced through the main domain (
captzapp.com) that it would work.

Does this make any sense?  Could it possibly be as easy as hardcoding the
rewrite rules to go to the main domain?

Thanks for the help with this.
Jeff

On Wed, Sep 2, 2015 at 8:13 AM, Justin Greer <notifications@github.com>
wrote:

> The main issue with is with how WP OAuth Server utilizes tables in the DB.
> It currently is not setup to handle multi blog which will cause all kinds
> of unknown headaches when trying to get it to work properly.
>
> You error "Token is not registered' must be custom as I am not sure it is
> even in the core code base.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/justingreerbbi/wordpress-oauth-server/issues/28#issuecomment-137095587>
> .
>



-- 
Jeff Wells
+506-8845-5993

**Comment by justingreerbbi** [comment]
You are correct. In a network setup, users all are under the main sites user base. The table is slightly different but it will work. The main issue is for WP OAuth Server is that it does not prohibit cross site jumping. Currently it can not see which blog ID the user has rights to. This feature is something that  have been wanting to explore for some time but have been wrapped up in other matters.

You could write a rewrite in the htaccess possibly that would redirect the incoming OAuth request to the main site. There is some many variables on play that I am not sure what would work and what would not. 
It is definitely something that I want to look into more. Maybe here by the end of the year and if a developer is feeling jolly! :) Anyone is more than welcome to fork and make a version for MS if they would like.

**Comment by hefejeff** [comment]
Thanks for the reply.  If I come up with a solution I will share...

I am going to try changing the following code in the plugin I am using.

add_rewrite_rule(
'^oauth1/authorize/?$','/index.php?json_oauth_route=authorize','top' );

*Change: (Domain Hardcode for now)*

add_rewrite_rule( '^oauth1/authorize/?$','
http://captapp.com/index.php?json_oauth_route=authorize','top' );

On Wed, Sep 2, 2015 at 2:44 PM, Justin Greer <notifications@github.com>
wrote:

> You are correct. In a network setup, users all are under the main sites
> user base. The table is slightly different but it will work. The main issue
> is for WP OAuth Server is that it does not prohibit cross site jumping.
> Currently it can not see which blog ID the user has rights to. This feature
> is something that have been wanting to explore for some time but have been
> wrapped up in other matters.
>
> You could write a rewrite in the htaccess possibly that would redirect the
> incoming OAuth request to the main site. There is some many variables on
> play that I am not sure what would work and what would not.
> It is definitely something that I want to look into more. Maybe here by
> the end of the year and if a developer is feeling jolly! :) Anyone is more
> than welcome to fork and make a version for MS if they would like.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/justingreerbbi/wordpress-oauth-server/issues/28#issuecomment-137238859>
> .
>



-- 
Jeff Wells
+506-8845-5993
