### ISSUE TITLE
Undefined class constant 'RESPONSE_TYPE_ID_TOKEN_TOKEN'

### ISSUE THREAD

**Issue by logankoester** [justingreerbbi/wordpress-oauth-server#31]
At the start of the login flow on `3.0.5` I'm getting a `500` response this in the logs:

> Undefined class constant 'RESPONSE_TYPE_ID_TOKEN_TOKEN' in www/wp-content/plugins/oauth2-provider/library/OAuth2/OpenID/Controller/AuthorizeController.php on line 82" while reading response header from upstream

Relevant line: https://github.com/justingreerbbi/wordpress-oauth-server/blob/master/library/OAuth2/OpenID/Controller/AuthorizeController.php#L82

**Comment by logankoester** [comment]
This problem was resolved after downgrading to `3.0.4`.

**Comment by justingreerbbi** [comment]
Thanks for the update. I am going to be taking a look here this weekend. Can you provide you server OS, and PHP version as well as the action that you are doing when this error is thrown?
