### ISSUE TITLE
404 /oauth/authorize

### ISSUE THREAD

**Issue by stevenmwade** [justingreerbbi/wordpress-oauth-server#32]
Going to settings and resetting the permalinks does not happening and changing them manually to /oauth/{method} or ?oauth={method} still comes up with a 404 and /oauth/authorize not found.

**Comment by justingreerbbi** [comment]
Does the permalinks structure work for the site in general or is it isolated to just WP OAuth Server? If you are using an other plugins, deactivate them and try again.

404 even when default permalink is working is a big issue. Do you have a link you can provide to the WP instance in question?

**Comment by stevenmwade** [comment]
It's a brand new, blank word press site so we can test it before using it
on a real site. When we installed it, it never changed the permalink setup
when you went to settings. Is there a more specific way of changing the
permalinks to something that works? We are also linking to it from a node
server using the passport oauth2 complete for wordpress. Would it be more
beneficial to use it with WP REST API? Default works, such as when you
create a new post, but when using the passport oath2 complete for wordpress
it always gives a 404.

**Comment by justingreerbbi** [comment]
There is no specific way to set the permalinks. Setting the permalink to "Post name" is recommended. Be sure that the .htaccess file is writeable as well and present.
