### ISSUE TITLE
how to set the rewrite rules for nginx?

### ISSUE THREAD

**Issue by Manasseh-Zhou** [justingreerbbi/wordpress-oauth-server#33]
when i open
/oauth/authorize?response_type=code&client_id=TestClient&redirect_uri=https:/redirect-uri.com/cb/

it turns into
/oauth/authorize/?response_type=code&client_id=TestClient&redirect_uri=https:/redirect-uri.com/cb/

then the wordpress show me the index page instead of the json i want.

what should I do?

**Comment by justingreerbbi** [comment]
Sorry for being short. I am on my phone at the moment. You can use none permalink structure as well. 
Http://yoursite.com?oauth=authorize&....
--
Sent from myMail app for Android Tuesday, 11 August 2015, 06:20AM -04:00 from Jimmy Zhou < notifications@github.com> :

**Comment by justingreerbbi** [comment]
Closing this due to age.

**Comment by Manasseh-Zhou** [comment]
thx
