### ISSUE TITLE
Github out of sync

### ISSUE THREAD

**Issue by jvandijk** [justingreerbbi/wordpress-oauth-server#35]
Hello @justingreerbbi,

The github repository is out of sync with the actual plugin state. I have some additions I'd like to share for prelimary multisite support but these are now based of the current code which still is on 3.1.8.

**Comment by justingreerbbi** [comment]
Sorry for the confusion here on GH. The GH repo tends to fall behind due to the guidelines regarding plugins and the WP repo.

I will see about pushing an update to GH here soon.

**Comment by jvandijk** [comment]
Can you point me to those guidelines?

**Comment by justingreerbbi** [comment]
I could so swore there was a guideline about hosting plugins outside of .ORG but can not find it for the life of me. 

You are more than welcome to use the WordPress.org repo (http://plugins.svn.wordpress.org/oauth2-provider/) as your base. I will see about possibly hooking both together but the fact of the matter is, this repo is not priority. I do understand your though. I will sync here shortly.

Thanks

**Comment by justingreerbbi** [comment]
Synced to the latest version
