### ISSUE TITLE
`expires_in` being returned as a string in `/oauth/token`

### ISSUE THREAD

**Issue by jsonfry** [justingreerbbi/wordpress-oauth-server#39]
We're running 3.1.93 with Wordpress 4.4.1. When setting a custom expiry time in the admin interface the `expires_in` parameter is returned as a string, not a number. E.g.:

    {
      "access_token": "abc123",
      "expires_in": "86400",
      "token_type": "Bearer",
      "scope": "basic",
      "refresh_token": "def456"
    }

If you remove the custom value for expiry time then you get `expires_in` correctly as an `int`, e.g.

    {
      "access_token": "abc123",
      "expires_in": 3600,
      "token_type": "Bearer",
      "scope": "basic",
      "refresh_token": "def456"
    }

**Comment by justingreerbbi** [comment]
That will def trough an issue with OpenID clients. Thanks, I will have a look and see when we can get an update out.

Thanks

**Comment by justingreerbbi** [comment]
This issue has been address in 3.1.94 scheduled for release here shortly.

**Comment by jsonfry** [comment]
Cheers! 😀

**Comment by justingreerbbi** [comment]
Latest version pushed
