### ISSUE TITLE
Using refresh token doesn't return a new refresh token

### ISSUE THREAD

**Issue by jsonfry** [justingreerbbi/wordpress-oauth-server#40]
When using the refresh token as described here:

https://wp-oauth.com/knowledge-base/using-the-refresh-token/

All parameters except a new refresh token are returned. e.g.

<img width="733" alt="screen shot 2016-02-15 at 17 12 24" src="https://cloud.githubusercontent.com/assets/368400/13055540/d0902052-d407-11e5-80d1-0458acc13a05.png">

**Comment by justingreerbbi** [comment]
Have you tried the nightly build? Check out https://github.com/justingreerbbi/wordpress-oauth-server/tree/dev-nightly

**Comment by jsonfry** [comment]
I have not, currently running the latest version, 3.1.95. Is there something in the nightly that might address this?

**Comment by justingreerbbi** [comment]
Yes.

**Comment by jsonfry** [comment]
Great. I guess I'll give that a go. Any intention on release date?

**Comment by justingreerbbi** [comment]
Not really as of right now. I have been crazy business and have not had a chance to do full testing. Maybe this week someone. If not, then I would think in at least by the end of the month.

**Comment by jsonfry** [comment]
That does indeed fix it. Cheers.

**Comment by justingreerbbi** [comment]
You had my hopes up
