### ISSUE TITLE
WP OAuth Server is causing PUT requests to not pass any body parameters

### ISSUE THREAD

**Issue by saasen** [justingreerbbi/wordpress-oauth-server#45]
I have a problem where PUT requests to a separate plugin which extends the WP REST API v2. It doesn't recieve any body parameters when using PUT. Please see [this issue](https://github.com/WP-API/WP-API/issues/2451) for for information.

It seems like WP OAuth Server is reading from `php://input` and doesn't store this in `$HTTP_RAW_POST_DATA`. Please see [this issue](https://github.com/WP-API/WP-API/issues/2451) for the solution.

**Comment by justingreerbbi** [comment]
Thanks for pointing this out.

**Comment by justingreerbbi** [comment]
To keep compatibility with REST API I am going to add this in and fall back to `php://input`.  

FYI: $HTTP_RAW_POST_DATA has been deprecated since PHP 5.6 and has been removed in 7.0.0.

**Comment by saasen** [comment]
First of all, thanks alot for this. Will this be available for us using 3.1.*?
The problem in `php://input` can only be read from once in PHP < v5.6. We are running PHP v5.4.45 right now. I guess it's possible to upgrade our PHP version, but it seems like a good idea to fix this anyways. :+1:

**Comment by saasen** [comment]
Any update on this issue, @justingreerbbi?

**Comment by justingreerbbi** [comment]
$HTTP_RAW_POST_DATA was addressed in version 3.2.4 and in available for download in your wp admin panel.

**Comment by justingreerbbi** [comment]
Once you confirm it is working and or not working, please feel free to update/close this issue.

**Comment by saasen** [comment]
Oh. We're not running 3.2 or higher, as we bought the license right before you guys changed your licensing model. Our license is not valid for 3.2.

**Comment by justingreerbbi** [comment]
Well lets fix that ;).. Could you submit a new support ticket at https://wp-oauth.com/support/submit-ticket/. Lets get you setup on 3.2!

**Comment by justingreerbbi** [comment]
I would also like to point out the latest commit to this repo! https://github.com/justingreerbbi/wordpress-oauth-server/commit/11b86dd2307dab3a638327504e37af6763433c82

**Comment by saasen** [comment]
After the upgrade, it still does not work for me. I really don't know what's happening. :(

**Comment by saasen** [comment]
I tried to install PHP version 5.6+ instead and it works. Must still be something wrong where you are reading from the `php::/input` thingy somewhere.
I will try to update the solution to run on the latest PHP 5.6 version instead, but this is still a bug as I see it.

**Comment by justingreerbbi** [comment]
It is only a bug because of the backward compatibility issue with completely removed PHP functionality. I will updated documentation to state that WP REST API is supported but only with a not EOL PHP version .
